### PR TITLE
feat: Add homepage design

### PR DESCRIPTION
**Pull request by JHNLWHD**
Re: #1 

This PR includes the following:
- Set font theme
- Set color theme
- City Gov't of Zamboanga logo
- TextBox for Control Number
- Button for Verify Quarantine Pass
- Footer 

Screenshot_1589090035

### CODE REVIEW

**Review by responilla07 — CHANGES_REQUESTED** [review]
Make the font size of the footer a little smaller try set it to 16-18.
Add backdrop that used with from web.

**Comment by JHNLWHD** [comment]
@responilla07 here is the changes that you've requested

Screenshot_1589096731

**Comment by responilla07** [comment]
Also change the backdrop color for footer.

**Comment by JHNLWHD** [comment]
@responilla07 as your request

Screenshot_1589098037

**Comment by responilla07** [comment]
Nicesuu LGTM!

**Review by responilla07 — APPROVED** [review]
Wellplayed!

**Pull request merged**
